using Lolighter.Data.Structure;
using System.Collections.Generic;
using System.Linq;
using static Lolighter.Info.Helper;

namespace Lolighter.Algorithm
{
    internal class Arc
    {
        static public List<SliderData> CreateArc(List<ColorNote> notes)
        {
            // New list of Arc, generated by the method.
            List<SliderData> arc = new();
            
            // List to keep the notes per type
            List<ColorNote> blue = new();
            List<ColorNote> red = new();

            notes = notes.OrderBy(o => o.beat).ToList();

            // We need to sort the notes per type
            foreach (ColorNote note in notes)
            {
                if (note.color == ColorType.RED)
                {
                    red.Add(note);
                }
                else if (note.color == ColorType.BLUE)
                {
                    blue.Add(note);
                }
            }

            // Find the Arc
            arc.AddRange(FindArc(red));
            arc.AddRange(FindArc(blue));

            arc = arc.OrderBy(o => o.beat).ToList();

            return arc;
        }
    }
}
